# Generated by Django 3.1.2 on 2020-10-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offeer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offeer',
            new_name='Offer',
        ),
    ]
